### ISSUE TITLE
Cannot run td-setup; Python Folder Missing

### ISSUE THREAD

**Issue by corroc** [stacksjb/AlfredTodWorkflow#9] opened 2023-05-21 21:59 UTC
Hello! 
I followed all instructions downloading TOD (with Command Line Tools and config'ing API token).
Running TD-Setup, I get this error in Terminal:

Last login: Sun May 21 17:47:20 on ttys001
python3 setup.py
corysnider@Macbooks-MacBook-Air ~ % python3 setup.py
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/corysnider/setup.py': [Errno 2] No such file or directory
corysnider@Macbooks-MacBook-Air ~ % 

Trying to resolve what step I missed. Thank you for any intel!

**Comment by stacksjb** [comment] 2023-05-21 22:53
This is the second report I've had of this, so I'm gonna have to figure out what is going on. Even though it has a "Browse in terminal" that opens the correct workflow path, it seems that step is not working on other systems. I'm unable to reproduce so I'll have to troubleshoot further.

In the meantime, you can right click on the workflow, open in finder, then type in the "python3 setup.py" from there, or you can follow the "Manual setup" instructions.

**Comment by stacksjb** [comment] 2023-05-22 14:26
Ok - this should be fixed. A single parameter that is parsed is now passed in.

It was a combination of a difference in the way native Terminal vs iTerm handled passed-in commands, as well as the mulitple prompts being pased.

**Closed by stacksjb** 2023-05-22 14:26 UTC
