### ISSUE TITLE
tdsetup can't find setup.py

### ISSUE THREAD

**Issue by smagdali** [stacksjb/AlfredTodWorkflow#6] opened 2023-04-22 09:54 UTC
On mac, If you just download the workflow from the Releases page, and double-click on it (the typical way to install all other workflows) , tdsetup assumes that setup.py will be in your home folder, which it won't be. 

I had to clone the repo to get it. I see that it's included in the workflow bundle, so maybe you just need to fix the path.

```
Last login: Sat Apr 22 10:46:25 on ttys007
python3 setup.py
stefan@StefMacBookPro ~ % python3 setup.py
/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/stefan/setup.py': [Errno 2] No such file or directory
stefan@StefMacBookPro ~ % ```

**Comment by stacksjb** [comment] 2023-04-23 00:56
This is expected; did you run it using "tdsetup" from Alfred? When you run it from Alfred, it maps to workflow directory.

**Comment by stacksjb** [comment] 2023-04-23 01:01
Can you confirm this is an issue? I've tested and been unable to reproduce. The first step for td-setup is to navigate to the setup.py path, relative to the workflow bundle. So that should work.

**Comment by stacksjb** [comment] 2023-04-23 01:06
If you're still having issues, provide the debug log (run the workflow with the bug clicked in Alfred prefs, then copy the output) and I'll go from there.

**Comment by stacksjb** [comment] 2023-05-06 23:22
I haven't seen any response here, so closing this issue. If someone else reproduces this, please let me know.

**Closed by stacksjb** 2023-05-06 23:22 UTC
Labels: bug
